[package]
name = "catshell"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"
# ctrlc = "3.4.4"  # 用于捕获Ctrl+C信号
# 移除termion依赖，因为它在Windows上不兼容
# actix-files = "0.6.5"
# actix-web = "4.7.0"